[package]
name = "mystorers"
version = "0.1.0"
authors = ["Gregory Wint <gregwint95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thrift = "0.13.0"
